<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <RootNamespace>View</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>View.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="contacts_512px.png" />
    <None Remove="contacts_64x64.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Model\Model.csproj" />
    <ProjectReference Include="..\ViewModel\ViewModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="contacts_64x64.ico" />
    <Resource Include="contacts_512px.png" />
  </ItemGroup>

</Project>
